name: GravitasAlbum

options:
  bundleIdPrefix: com.gravitas

settings:
  base:
    SWIFT_VERSION: 5.9

targets:
  GravitasAlbum:
    type: application
    platform: visionOS
    deploymentTarget: "1.0"
    sources:
      - path: Album
        excludes:
          - CurvedLayout/CurvedLayoutKit/**
          - README.md
    dependencies:
      - target: CurvedLayoutKit
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.gravitas.GravitasAlbum
        MARKETING_VERSION: 0.1
        CURRENT_PROJECT_VERSION: 1

  CurvedLayoutKit:
    type: framework
    platform: visionOS
    deploymentTarget: "1.0"
    sources:
      - path: Album/CurvedLayout/CurvedLayoutKit/Sources/CurvedLayoutKit
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.gravitas.CurvedLayoutKit
